# Project: cleanning - [candy data]
### this notebook is for educational purpose . in this notebook we will do some cleanning

## Table of Contents
<ul>
<li><a href="#intro">Introduction</a></li>
<li><a href="#wrangling">wrangling</a></li>
  
</ul>

<a id='intro'></a>
## Introduction

### Dataset Description 

> i will go through candy data 2017 , this data has :
- Internal_ID
- Q1-Going Out?: Are you actually going trick or treating yourself? "has values `Yes or No`"
- Q2-Gender: It has four different options, `Femal ,Male ,Other ,I'd rather not say`
- Q3-Age: Numerical field
- Q4-Country: Text Field, but users have written their own version of the names. Example, for America, there are entries such as USA, us, US, America so we should consider that while cleanning
- Q5-State/Province: Text Field, but users have written their own version of the names. Same as the country data.
- Q6-Joy Or Despair: All kinds of chocolate bars are the questions with three distinct options to choose from (Joy, Meh, Despair).
- Q7-Joy Other: Text Field to write items not included above that give you JOY. Lots of missing values.
- Q8-Despair Other: Text Field ti write items not included above that give you DESPAIR. Lots of missing values.
- Q9-Other Comments: Text Field. Lots of missing values.
- Q10-Dress: Binary field. Missing values present
- Unnamed: 113
- Q11-Day: Binary Answer Field. Missing values present

# 1- import packages and load data

In [44]:
import pandas as pd
import numpy as np
import warnings
warnings.simplefilter("ignore")
#from fuzzywuzzy import process ,fuzz
df=pd.read_excel("candy.xlsx")

<a id='wrangling'></a>
## Data Wrangling



### General Properties

# 2- show some general properties for the data

In [28]:
#df.info()
#df.describe()
#df.isna().sum()
df.shape

(2460, 120)

# 3- write summary about what you get form the above functions
> #### tips : this summary can be about : if there is any missing values , if there a wrong data type , if there a wrong range of values , ....

In [ ]:
# they are lots of missing values in each column 
#they are  many types of the mean in country

# cleaning

### 4- drop all the useless columns and  rows with too much NaN , 
> tip : useless columns can be like `Internal ID`and can be also columns with too much NaN 
- rename columns for easy access

In [45]:

df.rename(columns={"Internal ID":"id","Q1: GOING OUT?":"out","Q2: GENDER":"gender","Q3: AGE":"age","Q4: COUNTRY":"country","Q5: STATE, PROVINCE, COUNTY, ETC":"state","Q6 | 100 Grand Bar":"t1","Q6 | Anonymous brown globs that come in black and orange wrappers	(a.k.a. Mary Janes)":"t2","Q6 | Any full-sized candy bar":"t3","Q6 | Black Jacks":"t4","Q6 | Bonkers (the candy)":"t5","Q6 | Bonkers (the board game)":"t6","Q6 | Bottle Caps":"t7","Q6 | Box'o'Raisins":"t8","Q6 | Broken glow stick":"t9","Q6 | Butterfinger":"t10","Q6 | Cadbury Creme Eggs":"t11","Q6 | Candy Corn":"t12","Q6 | Candy that is clearly just the stuff given out for free at restaurants":"t13","Q6 | Caramellos":"t14","Q6 | Cash, or other forms of legal tender":"t15","Q6 | Chardonnay":"t16","Q6 | Chick-o-Sticks (we don’t know what that is)":"t17","Q6 | Chiclets":"t18","Q6 | Coffee Crisp":"t19","Q6 | Creepy Religious comics/Chick Tracts":"t20","Q6 | Dental paraphenalia":"t21","Q6 | Dots":"t22","Q6 | Dove Bars":"t23","Q6 | Fuzzy Peaches":"t24","Q6 | Generic Brand Acetaminophen":"t25","Q6 | Glow sticks":"t26","Q6 | Goo Goo Clusters":"t27","Q6 | Good N' Plenty":"t28","Q6 | Gum from baseball cards":"t29","Q6 | Gummy Bears straight up":"t30","Q6 | Hard Candy":"t31","Q6 | Healthy Fruit":"t32","Q6 | Heath Bar":"t33","Q6 | Hershey's Dark Chocolate":"t34","Q6 | Hershey’s Milk Chocolate":"t35","Q6 | Hershey's Kisses":"t36","Q6 | Hugs (actual physical hugs)":"t37","Q6 | Jolly Rancher (bad flavor)":"t38","Q6 | Jolly Ranchers (good flavor)":"t39","Q6 | JoyJoy (Mit Iodine!)":"t40","Q6 | Junior Mints":"t41","Q6 | Senior Mints":"t42","Q6 | Kale smoothie":"t43","Q6 | Kinder Happy Hippo":"t44","Q6 | Kit Kat":"t45","Q6 | LaffyTaffy":"t46","Q6 | LemonHeads":"t47","Q6 | Licorice (not black)":"t48","Q6 | Licorice (yes black)":"t49","Q6 | Lindt Truffle":"t50","Q6 | Lollipops":"t51","Q6 | Mars":"t52","Q6 | Maynards":"t53","Q6 | Mike and Ike":"t54","Q6 | Milk Duds":"t55","Q6 | Milky Way":"t56","Q6 | Regular M&Ms":"t57","Q6 | Peanut M&M’s":"t58","Q6 | Blue M&M's":"t59","Q6 | Red M&M's":"t60","Q6 | Green Party M&M's":"t61","Q6 | Independent M&M's":"t62","Q6 | Abstained from M&M'ing.":"t63","Q6 | Minibags of chips":"t64","Q6 | Mint Kisses":"t65","Q6 | Mint Juleps":"t66","Q6 | Mr. Goodbar":"t67","Q6 | Necco Wafers":"t68","Q6 | Nerds":"t69","Q6 | Nestle Crunch":"t70","Q6 | Now'n'Laters":"t71","Q6 | Peeps":"t72","Q6 | Pencils":"t73","Q6 | Pixy Stix":"t74","Q6 | Real Housewives of Orange County Season 9 Blue-Ray":"t75","Q6 | Reese’s Peanut Butter Cups":"t76","Q6 | Reese's Pieces":"t77","Q6 | Reggie Jackson Bar":"t78","Q6 | Rolos":"t79","Q6 | Sandwich-sized bags filled with BooBerry Crunch":"t80","Q6 | Skittles":"t81","Q6 | Smarties (American)":"t82","Q6 | Smarties (Commonwealth)":"t83","Q6 | Snickers":"t84","Q6 | Sourpatch Kids (i.e. abominations of nature)":"t85","Q6 | Spotted Dick":"t86","Q6 | Starburst":"t87","Q6 | Sweet Tarts":"t88","Q6 | Swedish Fish":"t89","Q6 | Sweetums (a friend to diabetes)":"t90","Q6 | Take 5":"91","Q6 | Tic Tacs":"t92","Q6 | Those odd marshmallow circus peanut things":"t93","Q6 | Three Musketeers":"t94","Q6 | Tolberone something or other":"t95","Q6 | Trail Mix":"t96","Q6 | Twix":"t97","Q6 | Vials of pure high fructose corn syrup, for main-lining into your vein":"98","Q6 | Vicodin":"t99","Q6 | Whatchamacallit Bars":"t100","Q6 | White Bread":"t101","Q6 | Whole Wheat anything":"t102","Q6 | York Peppermint Patties":"t103","Q7: JOY OTHER":"joy","Q8: DESPAIR OTHER":"despair","Q9: OTHER COMMENTS":"comment","Q10: DRESS":"dress","":"emp","Q11: DAY":"day","Q12: MEDIA [Daily Dish]":"dish","Q12: MEDIA [Science]":"science","Q12: MEDIA [ESPN]":"espn","Q12: MEDIA [Yahoo]":"yahoo","Click Coordinates (x, y)":"coor"},inplace=True)
df.drop(columns=["id","dish","espn","yahoo","comment","despair","joy"],axis=1,inplace=True)
df.dropna(axis=0,thresh=50,inplace=True)

df.shape

(1783, 113)

### 5 - clean `going out` column 
> tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [30]:
out=df["out"].mode()
df['out']=df['out'].fillna(out)
df

,out,gender,age,country,state,t1,t2,t3,t4,t5,...,t102,t103,joy,despair,comment,dress,Unnamed: 113,day,science,coor
1,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,DESPAIR,DESPAIR,Mounds,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,1.0,"(84, 25)"
3,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,DESPAIR,DESPAIR,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,Raisins can go to hell,White and gold,NaN,Sunday,1.0,"(75, 23)"
4,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,DESPAIR,JOY,NaN,NaN,NaN,White and gold,NaN,Friday,1.0,"(70, 10)"
5,No,Male,NaN,NaN,NaN,JOY,DESPAIR,JOY,NaN,NaN,...,DESPAIR,JOY,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"(75, 23)"
7,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,...,DESPAIR,DESPAIR,using my elbows to get in front of the little ...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,NaN,Friday,1.0,"(55, 5)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2454,No,Female,26,USA,Michigan,JOY,MEH,JOY,DESPAIR,MEH,...,MEH,JOY,NaN,NaN,NaN,White and gold,NaN,Friday,1.0,"(68, 39)"
2455,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,DESPAIR,MEH,Mounds,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN
2456,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,NaN,...,MEH,JOY,NaN,Capers,NaN,Blue and black,NaN,Friday,1.0,"(70, 26)"
2457,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,DESPAIR,MEH,Tiny bottles of maple syrup as given out by Cr...,NaN,NaN,Blue and black,NaN,Friday,1.0,"(67, 35)"
2459,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,DESPAIR,JOY,NaN,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,NaN,"(19, 26)"

In [31]:
out=df["out"].mode()
out2=df.fillna({"out":out})
out2

,out,gender,age,country,state,t1,t2,t3,t4,t5,...,t102,t103,joy,despair,comment,dress,Unnamed: 113,day,science,coor
1,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,DESPAIR,DESPAIR,Mounds,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,1.0,"(84, 25)"
3,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,DESPAIR,DESPAIR,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,Raisins can go to hell,White and gold,NaN,Sunday,1.0,"(75, 23)"
4,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,DESPAIR,JOY,NaN,NaN,NaN,White and gold,NaN,Friday,1.0,"(70, 10)"
5,No,Male,NaN,NaN,NaN,JOY,DESPAIR,JOY,NaN,NaN,...,DESPAIR,JOY,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"(75, 23)"
7,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,...,DESPAIR,DESPAIR,using my elbows to get in front of the little ...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,NaN,Friday,1.0,"(55, 5)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2454,No,Female,26,USA,Michigan,JOY,MEH,JOY,DESPAIR,MEH,...,MEH,JOY,NaN,NaN,NaN,White and gold,NaN,Friday,1.0,"(68, 39)"
2455,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,DESPAIR,MEH,Mounds,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN
2456,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,NaN,...,MEH,JOY,NaN,Capers,NaN,Blue and black,NaN,Friday,1.0,"(70, 26)"
2457,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,DESPAIR,MEH,Tiny bottles of maple syrup as given out by Cr...,NaN,NaN,Blue and black,NaN,Friday,1.0,"(67, 35)"
2459,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,DESPAIR,JOY,NaN,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,NaN,"(19, 26)"

### 6 - clean ` gender` column 
> tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [32]:
df['gender']=df['gender'].fillna("unknown")
df

,out,gender,age,country,state,t1,t2,t3,t4,t5,...,t102,t103,joy,despair,comment,dress,Unnamed: 113,day,science,coor
1,No,Male,44,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,DESPAIR,DESPAIR,Mounds,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,1.0,"(84, 25)"
3,No,Male,40,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,DESPAIR,DESPAIR,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,Raisins can go to hell,White and gold,NaN,Sunday,1.0,"(75, 23)"
4,No,Male,23,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,DESPAIR,JOY,NaN,NaN,NaN,White and gold,NaN,Friday,1.0,"(70, 10)"
5,No,Male,NaN,NaN,NaN,JOY,DESPAIR,JOY,NaN,NaN,...,DESPAIR,JOY,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"(75, 23)"
7,No,Male,33,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,...,DESPAIR,DESPAIR,using my elbows to get in front of the little ...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,NaN,Friday,1.0,"(55, 5)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2454,No,Female,26,USA,Michigan,JOY,MEH,JOY,DESPAIR,MEH,...,MEH,JOY,NaN,NaN,NaN,White and gold,NaN,Friday,1.0,"(68, 39)"
2455,No,Male,24,USA,MD,JOY,DESPAIR,MEH,DESPAIR,DESPAIR,...,DESPAIR,MEH,Mounds,Fruit Stripe Gum,NaN,White and gold,NaN,Friday,NaN,NaN
2456,No,Female,33,USA,New York,MEH,DESPAIR,JOY,NaN,NaN,...,MEH,JOY,NaN,Capers,NaN,Blue and black,NaN,Friday,1.0,"(70, 26)"
2457,No,Female,26,USA,Tennessee,MEH,DESPAIR,JOY,DESPAIR,MEH,...,DESPAIR,MEH,Tiny bottles of maple syrup as given out by Cr...,NaN,NaN,Blue and black,NaN,Friday,1.0,"(67, 35)"
2459,No,Female,66,usa,Pennsylvania,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,...,DESPAIR,JOY,NaN,NaN,"You hit all my chocolate highlights, and broug...",White and gold,NaN,Sunday,NaN,"(19, 26)"

### 7 - clean ` age` column 
> tip : note the type of age column , and NaN values
 - try to use `to_numeric` 
 - tip : you should choose which best value to put in place of these NaNs ( mean, median, ....etc)

In [33]:
df["age"]=pd.to_numeric(df["age"], errors ='coerce')
median=df["age"].median()
df['age']=df['age'].fillna(median)
df.head(5)

,out,gender,age,country,state,t1,t2,t3,t4,t5,...,t102,t103,joy,despair,comment,dress,Unnamed: 113,day,science,coor
1,No,Male,44.0,USA,NM,MEH,DESPAIR,JOY,MEH,DESPAIR,...,DESPAIR,DESPAIR,Mounds,NaN,Bottom line is Twix is really the only candy w...,White and gold,NaN,Sunday,1.0,"(84, 25)"
3,No,Male,40.0,us,or,MEH,DESPAIR,JOY,MEH,MEH,...,DESPAIR,DESPAIR,"Reese's crispy crunchy bars, 5th avenue bars, ...",NaN,Raisins can go to hell,White and gold,NaN,Sunday,1.0,"(75, 23)"
4,No,Male,23.0,usa,exton pa,JOY,DESPAIR,JOY,DESPAIR,MEH,...,DESPAIR,JOY,NaN,NaN,NaN,White and gold,NaN,Friday,1.0,"(70, 10)"
5,No,Male,42.0,NaN,NaN,JOY,DESPAIR,JOY,NaN,NaN,...,DESPAIR,JOY,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"(75, 23)"
7,No,Male,33.0,canada,ontario,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,...,DESPAIR,DESPAIR,using my elbows to get in front of the little ...,when the little kids get the big chocolate bar...,"first person to give out cans of beer, wins",Blue and black,NaN,Friday,1.0,"(55, 5)"

### 8 - clean ` country` column
> tip : note that country column has country names with different writing ways 
  - use fuzzywuzzy to deal with this problem
  - you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [ ]:
choices= pd.DataFrame( {"count" : ["United States"]})
for c in choices["count"]:
    matches=process.extract(c,df["country"],limit=df.shape[0])
    for match in matches:
        if match[1]>=45:
            df.loc[df["country"]==match[0],"country"] = c

In [ ]:
df["country"].head(5)

In [ ]:
df['country']=df['country'].fillna(df["country"].mode())
df["country"].head(5)

### 9 - clean ` area` column
> tip : area column has the same problem as country columns , but looking at all it's unique values may give us another way to deal with it rather than try to fix it

In [34]:
df.drop(columns=["state"],axis=1,inplace=True)

### 10 - clean ` Q6` columns
>- tip : Q6 has all kinds of chocolate bars and questions with three distinct options to choose from (Joy, Meh, Despair).
- so all the column that has Q6 is a candy name , so you should go through all these column and you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [35]:

m=(df.iloc[:,5:108]).mode()
df.iloc[:,5:108]=(df.iloc[:,5:108]).fillna(m)
(df.iloc[:,5:108]).head(5)

,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,...,t95,t96,t97,98,t99,t100,t101,t102,t103,joy
1,DESPAIR,JOY,MEH,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,MEH,...,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,Mounds
3,DESPAIR,JOY,MEH,MEH,DESPAIR,MEH,DESPAIR,DESPAIR,MEH,MEH,...,JOY,MEH,JOY,DESPAIR,JOY,JOY,DESPAIR,DESPAIR,DESPAIR,"Reese's crispy crunchy bars, 5th avenue bars, ..."
4,DESPAIR,JOY,DESPAIR,MEH,DESPAIR,MEH,DESPAIR,DESPAIR,MEH,MEH,...,JOY,DESPAIR,JOY,MEH,JOY,JOY,DESPAIR,DESPAIR,JOY,NaN
5,DESPAIR,JOY,NaN,NaN,NaN,MEH,MEH,DESPAIR,JOY,DESPAIR,...,JOY,MEH,JOY,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,NaN
7,DESPAIR,JOY,DESPAIR,DESPAIR,MEH,JOY,MEH,JOY,JOY,JOY,...,MEH,DESPAIR,JOY,JOY,MEH,DESPAIR,DESPAIR,DESPAIR,DESPAIR,using my elbows to get in front of the little ...

In [36]:
df.iloc[:,5:108] = df.iloc[:,5:108].fillna("unknown")
df.iloc[:,5:108] .head()

,t2,t3,t4,t5,t6,t7,t8,t9,t10,t11,...,t95,t96,t97,98,t99,t100,t101,t102,t103,joy
1,DESPAIR,JOY,MEH,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,MEH,...,JOY,DESPAIR,JOY,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,DESPAIR,Mounds
3,DESPAIR,JOY,MEH,MEH,DESPAIR,MEH,DESPAIR,DESPAIR,MEH,MEH,...,JOY,MEH,JOY,DESPAIR,JOY,JOY,DESPAIR,DESPAIR,DESPAIR,"Reese's crispy crunchy bars, 5th avenue bars, ..."
4,DESPAIR,JOY,DESPAIR,MEH,DESPAIR,MEH,DESPAIR,DESPAIR,MEH,MEH,...,JOY,DESPAIR,JOY,MEH,JOY,JOY,DESPAIR,DESPAIR,JOY,unknown
5,DESPAIR,JOY,unknown,unknown,unknown,MEH,MEH,DESPAIR,JOY,DESPAIR,...,JOY,MEH,JOY,DESPAIR,DESPAIR,JOY,DESPAIR,DESPAIR,JOY,unknown
7,DESPAIR,JOY,DESPAIR,DESPAIR,MEH,JOY,MEH,JOY,JOY,JOY,...,MEH,DESPAIR,JOY,JOY,MEH,DESPAIR,DESPAIR,DESPAIR,DESPAIR,using my elbows to get in front of the little ...

### 11 - clean ` dress` column
>tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [37]:
df['dress']=df['dress'].replace({np.nan:"unknown"})
df["dress"].head(5)

1    White and gold
3    White and gold
4    White and gold
5           unknown
7    Blue and black
Name: dress, dtype: object

### 12 - clean ` day` column
>tip : you should choose which best value to put in place of these NaNs ( mode, unknown,other ....etc)

In [38]:
df['day']=df['day'].fillna(df["day"].mode()[0])
df["day"].head(5)

1    Sunday
3    Sunday
4    Friday
5    Friday
7    Friday
Name: day, dtype: object

### 13 - check
> after finish cleaning you should make sure your data is clean and that :
- there is no wrong data type
- there is no NaN values 
- all the column are cleaing and ready for the next step `EDA`

In [46]:
df['science']=df['science'].fillna(df["science"].mode()[0])
df["science"].head(5)

1    1.0
3    1.0
4    1.0
5    1.0
7    1.0
Name: science, dtype: float64

### 14 - write a summary about all the cleaning steps

1\ import using libraries
2\rename columns to sample it 
3\remove all columns and rows with so much nan and useless data
4\clean each column to remove nan values